version: '3.7'
services:
  web:
    build: .
    container_name: web
    restart: always
    ports:
      - 8888:80
    volumes:
      - ./html:/var/www/html
  db:
    image: mariadb:latest
    container_name: db
    restart: always
    volumes:
      - wordpress_db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=AnythingYouDLike
volumes:
  wordpress_db: {}
